---
name: "Prevent Sleep"
guid: "d6b0196a-9885-4d87-b25c-562a57ebbe0b"
version: "0.2.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Prevent system sleep when streaming"
description: "Prevents the system from entering sleep mode when there are active streams."
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.PreventSleep.dll"
changelog: |-
  - changelog
