---
name: "Prevent Sleep"
guid: "d6b0196a-9885-4d87-b25c-562a57ebbe0b"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Prevent the system from entering sleep mode when there are active streams"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.PreventSleep.dll"
changelog: >
  changelog
