<Project>
    <PropertyGroup>
        <VersionPrefix>0.4.0</VersionPrefix>
        <!-- Enable for a prerelease, comment out for a full release -->
        <VersionSuffix>-alpha.1</VersionSuffix>

        <Version>$(VersionPrefix)$(VersionSuffix)</Version>
        <FileVersion>$(VersionPrefix).0</FileVersion>
        <InformationalVersion>$(Version)</InformationalVersion>
    </PropertyGroup>
</Project>
